### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by pmakin** [MrCosmo666/Teeworlds-MRPG#19]
- [ ] Magic stuff

- [ ] Special abilities for different classes

- [ ] New location (with new npcs, quests and etc.)

- [x] New npc that will upgrade strength (in Elphinia)

- [ ] Selling potatoes feature (HOT) P.S. Make farmer cooldown in 1 in-game day

- [x] Discord PRC P.S. Nickname, Gold, Guild, Location, Level

- [x] Hash passwords
