### ISSUE TITLE
Progress to update 2.0.1

### ISSUE THREAD

**Issue by kurosio** [MrCosmo666/Teeworlds-MRPG#37]
# Patch notes 
_Assignees  can edit a issue in case of progress or changes, as well as attach a link to the PR under each task_
Release type | Current version | Update to version
------ | ---- | -----
Game | 2.0.0 | 2.0.1
Protocol | 1024 | 1025

## Shared side
- [x] Changing version control (done  #36)
- [x] Demo broken what recorded from MRPG server&client for Teeworlds Vanilla (done #44)

## Client side
- [x] Disable input on inactive clients (done #43)
- [x] Update to master Teeworlds branch (done #49)

## Server side
- [x] Balancing Enchantment (done #36)
- [x] Balancing Skill Points (done #36)
- [x] Refactoring structures ItemsJob (done  #36)
- [x] Refactoring structures SkillJob (done #46)
- [x] Some correction and empty problem in the menu CraftsJob (done  #36)
- [x] Fix a bug with saving during client exit (done  #36)
- [x] Ability to view top players in level and wealthy from discord bot (done #39)
- [x] Redesign the command system preferably with support for commands system from the Teeworlds update (done #42)
- [x] Worlds array rid of fixed array  (example list or vector [Link to the code](https://github.com/MrCosmoTW/Teeworlds-MRPG/blob/master/src/engine/server/server.h#L105)) (done #51)
it is also desirable to have the structure of the world its name
- [x] Make addition in CMakeLists.txt for discord_deps from bam.lua (done #68)

## Protocol side
No changes

## Database changes are attached to Update 
Changes from #36 
```sql
-- remove EnchantMax field
ALTER TABLE `tw_items_list` DROP `EnchantMax`;

-- set strength how unfield (this will not address 'tw_accounts' Strength) and drop it from 'tw_accounts_data'
UPDATE `tw_attributs` SET `field_name` = 'unfield' WHERE `tw_attributs`.`ID` = 4;
ALTER TABLE `tw_accounts_data` DROP `Strength`;

-- drop enum_craft_tabs (unused only confuses)
DROP TABLE `ENUM_CRAFT_TABS`;
```
Changes from #49 
```sql
-- change the Strength type to hard where is the power of each weapon
UPDATE `tw_attributs` SET `at_type` = '4' WHERE `tw_attributs`.`ID` = 4;
```
```sql
-- import it without check foreign keys
-- some corrections with the attribute structure
SET foreign_key_checks = 0;

DROP TABLE `tw_attributs`;

CREATE TABLE `tw_attributs` (
  `ID` int(11) PRIMARY KEY NOT NULL,
  `name` varchar(32) NOT NULL,
  `field_name` varchar(32) NOT NULL DEFAULT 'unfield',
  `price` int(11) NOT NULL,
  `at_type` int(11) NOT NULL COMMENT '0.tank1.healer2.dps3.weapon4.hard5.jobs 6. others',
  `divide` int(11) NOT NULL DEFAULT 0 COMMENT 'if the value is set the final stats will be divided by the set number'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `tw_attributs` (`ID`, `name`, `field_name`, `price`, `at_type`, `divide`) VALUES
(1, 'Shotgun Spread', 'SpreadShotgun', 100, 3, 0),
(2, 'Grenade Spread', 'SpreadGrenade', 100, 3, 0),
(3, 'Rifle Spread', 'SpreadRifle', 100, 3, 0),
(4, 'Strength', 'unfield', -1, 4, 10),
(5, 'Dexterity', 'Dexterity', 1, 2, 5),
(6, 'Crit Dmg', 'CriticalHit', 1, 2, 5),
(7, 'Direct Crit Dmg', 'DirectCriticalHit', 1, 2, 5),
(8, 'Hardness', 'Hardness', 1, 0, 5),
(9, 'Lucky', 'Lucky', 1, 0, 5),
(10, 'Piety', 'Piety', 1, 1, 5),
(11, 'Vampirism', 'Vampirism', 1, 1, 5),
(12, 'Ammo Regen', 'AmmoRegen', 1, 3, 5),
(13, 'Ammo', 'Ammo', 30, 3, 0),
(14, 'Efficiency', 'unfield', -1, 5, 0),
(15, 'Extraction', 'unfield', -1, 5, 0),
(16, 'Hammer Power', 'unfield', -1, 4, 10),
(17, 'Gun Power', 'unfield', -1, 4, 10),
(18, 'Shotgun Power', 'unfield', -1, 4, 10),
(19, 'Grenade Power', 'unfield', -1, 4, 10),
(20, 'Rifle Power', 'unfield', -1, 4, 10),
(21, 'Lucky items', 'unfield', -1, 6, 5);

SET foreign_key_checks = 1;
```

```sql
-- Progress -> Step
ALTER TABLE `tw_accounts_quests` CHANGE `Progress` `Step` INT(11) NOT NULL DEFAULT **'1';**
```

## Things needed to be done for this update
- [x] Due to #31 it's required to execute the "convert_passwords" rcon command to hash existing passwords
