### ISSUE TITLE
Progress to update 2.0.2

### ISSUE THREAD

**Issue by kurosio** [MrCosmo666/Teeworlds-MRPG#70]
# Patch notes 
_Assignees  can edit a issue in case of progress or changes, as well as attach a link to the PR under each task_
Release type | Current version | Update to version
------ | ---- | -----
Game | 2.0.1 | 2.0.2
Protocol | 1025 | no change

## Shared side
No changes

## Client side
No changes

## Server side
- [x] Animations are getting lost the server behaves strangely during downtime (done #74)
- [x] Implement the 24-hour format and the ability to control it (done #72)

## Protocol side
No changes

## Postponed
- [ ] Implement discord activity points (issue https://github.com/MrCosmo666/Teeworlds-MRPG/issues/67)
- [ ] An error when a client crashes may cause its data to not be cleared (message from discord ’em... What should I do? I can't login my account again when I lost connection on downloading next map. TuT
message: "The account is already in the game!"’)
- [ ] CMake headers for dependency search are broken (issue https://github.com/MrCosmo666/Teeworlds-MRPG/issues/66)

## Database changes are attached to Update
