### ISSUE TITLE
Progress to update 2.0.3

### ISSUE THREAD

**Issue by kurosio** [MrCosmo666/Teeworlds-MRPG#75]
# Patch notes 
_Assignees  can edit a issue in case of progress or changes, as well as attach a link to the PR under each task_
Release type | Current version | Update to version
------ | ---- | -----
Game | 2.0.2 | 2.0.3
Protocol | 1025 | no change

## Client side
- [x] Fix client crashes when using CChain from console (done #81)
- [x] Fix minor visual bugs and glimpses of RPG dialogs at first launch (done #81)

## Server side
- [x] Fix discord bot sometimes MENU appears instead of the text and bot does not update the status (done #80)
- [x] Convert quest players steps to json (done #79)

## Protocol side
No changes

## Postponed
- [ ] CMake headers for dependency search are broken (issue https://github.com/MrCosmo666/Teeworlds-MRPG/issues/66)
- [ ] Implement discord activity points (issue https://github.com/MrCosmo666/Teeworlds-MRPG/issues/67)
- [ ] An error when a client crashes may cause its data to not be cleared (message from discord ’em... What should I do? I can't login my account again when I lost connection on downloading next map. TuT
message: "The account is already in the game!"’)

## Things needed to be done for this update
- [x] Due to #79 it's required to execute the "convert_players_steps" rcon command to convert quest steps to json
