### ISSUE TITLE
Progress to update 2.0.4

### ISSUE THREAD

**Issue by kurosio** [MrCosmo666/Teeworlds-MRPG#84]
# Patch notes 
_Assignees  can edit a issue in case of progress or changes, as well as attach a link to the PR under each task_
Release type | Current version | Update to version
------ | ---- | -----
Game | 2.0.3 | 2.0.4
Protocol | 1025 | no change

## Shared side
- [x] CMake headers for dependency search are broken (issue #66)
- [x] Missed libdiscordgamesdk.so to pack linux (issue #108)
## Client side
- [x] Make win32 supported client (issue #30 done #94)

## Server side
- [ ] Implement discord activity points (issue #67)
- [ ] An error when a client crashes may cause its data to not be cleared (message from discord ’em... What should I do? I can't login my account again when I lost connection on downloading next map. TuT
message: "The account is already in the game!"’)
- [x] Remove rcon quest step converter (from #79 done #85)
- [x] Going thru walls with skill (issue #87 done #89)
- [x] Promo code system (issue #90)

## Protocol side
No changes

## Postponed
No changes

## Database changes are attached to Update 
- [ ] Higher drop chance for some items (issue #65)

## Things needed to be done for this update
No changes
